{{- if .Values.traefikIngress.tls.enabled}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-tls-certificate
spec:
  secretName: {{ .Values.traefikIngress.tls.secretName }}
  dnsNames:
    {{- range .Values.traefikIngress.routes }}
    - {{ .host }}
    {{- end }}
  issuerRef:
    name: {{ .Values.certResolver.issuerRef.name }}
    kind: {{ .Values.certResolver.issuerRef.kind }}

{{- end }}
