{{- if .Values.ingress.enabled }}
{{- if .Values.ingress.clusterIssuer }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-ssl
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}

---
{{- $namespace := .Release.Namespace }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.clusterIssuer }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ $namespace }}-redirect-ssl@kubernetescrd
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    {{- end }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  {{- if .Values.ingress.clusterIssuer }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ .Release.Name }}-cert
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "jellyfin.fullname" . }}
            port:
              number: {{ .Values.service.port }}

{{- end }}
