{{- if .Values.traefikIngress.enabled }}
{{- $fullName := include "jellyfin.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $namespace := .Values.namespace -}}
{{- if .Values.traefikIngress.sslRedirect }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-ssl-redirect
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
{{- end }}
