apiVersion: v1
kind: Service
metadata:
  name: {{ include "servarr.prowlarr.fullname" . }}
  {{- include "servarr.namespace" . | nindent 2 }}
  labels:
    {{- include "servarr.prowlarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prowlarr.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "servarr.prowlarr.matchLabels" . | nindent 4 }}
