{{- if .Values.radarr.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "servarr.radarr.serviceName" . }}
  {{- include "servarr.namespace" . | nindent 2 }}
  labels:
    {{- include "servarr.radarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.radarr.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "servarr.radarr.matchLabels" . | nindent 4 }}
{{- end }}
