{{- if .Values.prowlarr.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "servarr.prowlarr.serviceAccountName" . }}
  {{- include "servarr.namespace" . | nindent 2 }}
  labels:
    {{- include "servarr.prowlarr.labels" . | nindent 4 }}
  {{- with .Values.prowlarr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
