{{- if .Values.radarr.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "servarr.radarr.serviceAccountName" . }}
  {{- include "servarr.namespace" . | nindent 2 }}
  labels:
    {{- include "servarr.radarr.labels" . | nindent 4 }}
  {{- with .Values.radarr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
