{{- if .Values.sonarr.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "servarr.sonarr.serviceAccountName" . }}
  {{- include "servarr.namespace" . | nindent 2 }}
  labels:
    {{- include "servarr.sonarr.labels" . | nindent 4 }}
  {{- with .Values.sonarr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
