# Default values for servarr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

radarr:
  fullnameOverride: ""
  #Container Name and selector
  name: "radarr"
  replicaCount: 1
  image:
    repository: lscr.io/linuxserver/radarr
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "5.2.6"


  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  podAnnotations: {}
  storage:
    enabled: false
    volumes:
      - name: media
        mountPath: /media
        spec:
          nfs:
            path: /path/to/media
            server: server-ip

      - name: data
        mountPath: /config
        capacity: 500Mi
        accessModes: ["ReadWriteOnce"]
        spec:
          persistentVolumeClaim:
            claimName: "radarr-pvc"


  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector: {}

  tolerations: []

  affinity: {}

  service: 
    port: 7878
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  serviceAccount:
    create: true
    name: ""
    annotations: {}

# Sonarr Configuration
sonarr:
  fullnameOverride: ""
  #Container Name and selector
  name: "sonarr"
  replicaCount: 1
  image:
    repository: lscr.io/linuxserver/sonarr
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "4.0.0"


  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  podAnnotations: {}
  storage:
    enabled: false
    volumes:
      - name: media
        mountPath: /media
        spec:
          nfs:
            path: /path/to/media
            server: servar-ip

      - name: data
        mountPath: /config
        capacity: 1Gi
        accessModes: ["ReadWriteOnce"]
        spec:
          persistentVolumeClaim:
            claimName: "sonarr-pvc"


  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector: {}

  tolerations: []

  affinity: {}

  service: 
    port: 8989
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  serviceAccount:
    create: true
    name: ""
    annotations: {}


# Prowlarr Configuration
prowlarr:
  fullnameOverride: ""
  #Container Name and selector
  name: "prowlarr"
  replicaCount: 1
  image:
    repository: lscr.io/linuxserver/prowlarr
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.10.5"


  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  podAnnotations: {}
  storage:
    enabled: false
    volumes:
      - name: data
        mountPath: /config
        capacity: 1Gi
        accessModes: ["ReadWriteOnce"]
        spec:
          persistentVolumeClaim:
            claimName: "prowlarr-pvc"

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector: {}

  tolerations: []

  affinity: {}

  service: 
    port: 9696
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  serviceAccount:
    create: true
    name: ""
    annotations: {}

environment:
  PUID: "1000"
  PGID: "1000"
  TZ: "America/New_York"

ingress:
  enabled: false
  clusterIssuer: "testing"
  hosts:
    radarr: example-1.com
    sonarr: example-2.com
    prowlarr: example-3.com
  annotations: {}




imagePullSecrets: []
nameOverride: ""





