{{- if .Values.ingress.enabled }}
{{- if .Values.ingress.clusterIssuer }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-ssl
  {{- include "servarr.namespace" . | nindent 2 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}

---
{{- $namespace := (include "servarr.namespace" .) | replace "namespace: " "" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.clusterIssuer }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ $namespace }}-redirect-ssl@kubernetescrd
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    {{- end }}
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
spec:
  {{- if .Values.ingress.clusterIssuer }}
  tls:
    - hosts:
      {{- range $key, $value := .Values.ingress.hosts }}
      - {{ $value }}
      {{- end }}
      secretName: {{ .Release.Name }}-cert

  {{- end }}
  rules:
  - host: {{ .Values.ingress.hosts.radarr }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "servarr.radarr.serviceName" . }}
            port:
              number: 80

  - host: {{ .Values.ingress.hosts.sonarr }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "servarr.sonarr.serviceName" . }}
            port:
              number: 80
              
  - host: {{ .Values.ingress.hosts.prowlarr }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "servarr.prowlarr.serviceName" . }}
            port:
              number: 80
{{- end }}
